name: Publish Linux

on:
  workflow_dispatch:
    inputs:
      upload-to-storage:
        description: 'Uploads to Azure storage'
        required: false
        default: '1'
        type: string
      run-linux-publish:
        description: 'Run the publish jobs vs just the build jobs'
        type: boolean
        default: false

jobs:
  publish:
    uses: electron/electron/.github/workflows/linux-pipeline.yml@main
    with:
      is-release: true
      gn-config: //electron/build/args/release.gn
      gn-build-type: release
      generate-symbols: true
      upload-to-storage: ${{ inputs.upload-to-storage }}
    secrets: inherit
