name: Build Linux

on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  build:
    uses: electron/electron/.github/workflows/linux-pipeline.yml@main
    with:
      is-release: false
      gn-config: //electron/build/args/testing.gn
      gn-build-type: testing
      generate-symbols: false
      upload-to-storage: '0'
    secrets: inherit
